skillMetadata:
  sections:
    - name: Login
      fields:
        - name: host
          type: text
          label: Host address
          value: ""
        - name: token
          type: password
          label: Long-Lived Access Token
          value: ""
    - name: Devices
      fields:
        - name: device_map
          type: text
          label: Device Map
